#!/usr/bin/env ruby.exe
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('../../server/config/application',  __FILE__)
require File.expand_path('../../server/config/boot',  __FILE__)
require 'rails/commands'
